const courses = [
  { name: "GSM" },
  { name: "XML" },
  { name: "PCI Standards" },
  { name: "Smart TV" },
  { name: "DNA fingerprinting" },
  { name: "MRPII" },
  { name: "WFC" },
  { name: "Type Rating" },
  { name: "Public Administration" },
  { name: "LSO" },
  { name: "Zuken" },
  { name: "Tunnels" },
  { name: "Rural Development" },
  { name: "KPI Dashboards" },
  { name: "Online Lead Generation" },
  { name: "On Location" },
  { name: "News Writing" },
  { name: "NCover" },
  { name: "Substance Use Disorders" },
  { name: "Fashion Illustration" },
  { name: "WPF Development" },
  { name: "Slide Preparation" },
  { name: "SharePoint" },
  { name: "DDI Certified Facilitator" },
  { name: "Basel II" },
  { name: "XQuery" },
  { name: "JPEG2000" },
  { name: "FX Derivatives" },
  { name: "Rheology" },
  { name: "Rhetorical Analysis" },
  { name: "Estimates" },
  { name: "Outpatient Orthopedics" },
  { name: "Lotus Domino" },
  { name: "Airline Ticketing" },
  { name: "SAP EBP" },
  { name: "iVantage" },
  { name: "Core FTP" },
  { name: "Payment by Results" },
  { name: "Blackberry Enterprise Server" },
  { name: "Novell" },
  { name: "CICS" },
  { name: "McData" },
  { name: "Japanese Language Proficiency Test" },
  { name: "Estimates" },
  { name: "ITIL Certified" },
  { name: "Vector Illustration" },
  { name: "TMA" },
  { name: "DVB-T" },
  { name: "PET-CT" },
  { name: "HUET" },
  { name: "VC-1" },
  { name: "Benefits Administration" },
  { name: "Alternative Investments" },
  { name: "ICD-9-CM" },
  { name: "NPV" },
  { name: "Timber" },
  { name: "Award Submissions" },
  { name: "VOD" },
  { name: "IETF" },
  { name: "VMware Certified Professional" },
  { name: "UCaaS" },
  { name: "Yacht Racing" },
  { name: "Teeth Whitening" },
  { name: "Aerodynamics" },
  { name: "DTT" },
  { name: "Urban Design" },
  { name: "Retail" },
  { name: "QS1" },
  { name: "RRIF" },
  { name: "Hair Care" },
  { name: "Electricity" },
  { name: "HMDA" },
  { name: "DMR" },
  { name: "GPS Units" },
  { name: "MPLAB" },
  { name: "Branding &amp; Identity" },
  { name: "Data Mining" },
  { name: "FTTP" },
  { name: "TTL" },
  { name: "NATO" },
  { name: "Experimentation" },
  { name: "EASA" },
  { name: "SDS-PAGE" },
  { name: "pgAdmin" },
  { name: "OMAP" },
  { name: "Strategic Communications" },
  { name: "Portraits" },
  { name: "Xcode" },
  { name: "Criminal Justice" },
  { name: "XSD" },
  { name: "MMI" },
  { name: "Transitional Justice" },
  { name: "VMware Infrastructure" },
  { name: "Strategic Thinking" },
  { name: "Keyboard Skills" },
  { name: "QAD" },
  { name: "Vtiger" },
  { name: "SSO" },
  { name: "Sleep Apnea" },
  { name: "Operational Oversight" },
];

module.exports = { courses };
